slience warnings of sklearn
EcoExtreML/Emulator pull request #20
Opened 2023-10-02 09:20 UTC by QianqianHan96

I slienced the warnings of sklearn in notebook . #16

2023-10-20 12:48 UTC, geek-yang requested changes
Looks good to me. Just a minor comment about the caching file. Please remove it from the PR, to keep the repo clean.

I didn't run the notebook myself but I checked your results. The warnings are gone. But I notice that you didn't add feature name as a row to the pandas dataframe. Just wonder what did you actually do to silent the warnings? Did you remove the feature names in the pickle model?

2023-10-20 12:48 UTC, geek-yang commented on 2daskParallel/.ipynb_checkpoints/1002_1year_10degree-checkpoint.ipynb
This is a caching file. To make the repo clean, it is better to exclude these files. Please remove the `.ipynb_checkpoints` folder in this PR.

Also for the [`.ipynb_checkpoints`](https://github.com/EcoExtreML/Emulator/tree/main/1sbatchParallel/.ipynb_checkpoints) folder in`1sbatchParallel`, just move it too.

Btw, if you add `.ipynb_checkpoints` in the `.gitignore`, then next time when you make commits these caching files won't be counted by git, which makes life easier 😉 .

2023-10-23 16:46 UTC, QianqianHan96 commented on 2daskParallel/.ipynb_checkpoints/1002_1year_10degree-checkpoint.ipynb
Thanks for your careful check, Yang. I have deleted all `.ipynb_checkpoints` folders in this PR and modified `.gitignore` as well. Please review the changes, Thanks!

2023-10-24 07:23 UTC, geek-yang approved these changes
Looks cool! Thanks for addressing my comments! Let's merge it!

2023-10-24 07:23 UTC, geek-yang commented
> > Looks good to me. Just a minor comment about the caching file. Please remove it from the PR, to keep the repo clean.
> > I didn't run the notebook myself but I checked your results. The warnings are gone. But I notice that you didn't add feature name as a row to the pandas dataframe. Just wonder what did you actually do to silent the warnings? Did you remove the feature names in the pickle model?
> 
> Hi Yang, I added feature names as a row in the following part (first screenshot is the old version and second screenshot is the new version), maybe you did not notice it. I did not remove feature names in the pickle model. Please let me know is this okay. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/90645468/277402860-e7d239b9-aa2f-40b2-8d9e-865d904dcae7.png) ![image](https://user-images.githubusercontent.com/90645468/277402911-fd2766b8-f149-4be5-ab51-fa41b5cfd0fc.png)

Indeed, I missed this line. Nice work!

2023-10-24 07:33 UTC, merged